name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=Your GetScreen Mail" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/tzt2jdqq91blq3c438jeh/down.bat?rlkey=qmbiwlxnkbzeakqkhwyxw2j6u&dl=0" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
